[rule]
description = """
Identifies an unexpected process accessing the password store of commonly used web browsers. Adversaries may steal
credentials from web browsers by reading files specific to the target browser.
"""
id = "f488cd1b-2407-4ec8-8705-7adf99ccbd33"
license = "Elastic License v2"
name = "Web Browser Credential Access via Unusual Process"
os_list = ["windows"]
version = "1.0.15"

query = '''
file where event.type == "access" and
 process.executable != null and
 file.name : ("Login Data", "logins.json", "signons.sqlite", "cookies.sqlite") and
 file.path : ("?:\\Users\\*", "\\??\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*\\Users\\*") and not

 /* browsers have variable install path %programfiles% and Users home folder */
 process.name : ("chrome.exe", "firefox.exe", "firefoxportable.exe", "brave.exe", "browser.exe", "dragon.exe", "iexplore.exe",
                "msedge.exe", "maxthon.exe", "microsoftedge.exe", "microsoftedgecp.exe", "microsoftedgesh.exe", "opera.exe",
				"vivaldi.exe", "palemoon.exe", "seamonkey.exe", "safari.exe", "waterfox.exe", "OneDrive.exe", "BCompare.exe",
				"thunderbird.exe", "certutil.exe", "chromium.exe", "UpdateBrowserForApp.exe", "MsMpEng.exe", "MpCopyAccelerator.exe",
				"CCleaner64.exe", "ESETOnlineScanner.exe", "detecttvsu.exe") and not
 process.executable :
          (
            /* third party programs common install path - requires local admin */
            "*\\Program Files\\*",
            "*\\Program Files (x86)\\*",

            /*
              dllhost.exe (IFileOperation like view/changing security permission of a file/folder).
              explorer.exe for directory and file discovery.
              SearchProtocolHost.exe is for file searches and indexing.
              browserexport is a legit utility that can be used to migrate browser data (but not decrypt pwd).
             */
            "*\\Windows\\explorer.exe",
            "*\\Windows\\System32\\dllhost.exe",
            "*\\Windows\\System32\\Robocopy.exe",
            "*\\Windows\\System32\\browserexport.exe",
            "*\\Windows\\System32\\SearchProtocolHost.exe"
	      ) and
   /* System virtual process */
  not process.pid == 4 and

  /* svchost instances running as non privileged user sid */
  not (process.executable : "*\\Windows\\System32\\svchost.exe" and process.parent.pid < 1000) and

  /* excluding privileged services and third party programs */
  not (user.id : ("S-1-5-18", "S-1-5-19", "S-1-5-20") and
       process.executable : ("?:\\Windows\\System32\\*.exe", "?:\\Program Files\\*.exe", "?:\\Program Files (x86)\\*.exe")) and

  not (process.name : "gener8.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\GENER8\\USER DATA\\DEFAULT\\LOGIN DATA") and
  not (process.name : "ccs.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\ENTERPRISEBANKSECUREBROWSER\\USER DATA\\DEFAULT\\LOGIN DATA") and 
  not (process.name : "epic.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\EPIC PRIVACY BROWSER\\USER DATA\\DEFAULT\\LOGIN DATA") and
  not (process.name : "ccss?st.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\ESERVISSECUREBROWSER\\USER DATA\\DEFAULT\\LOGIN DATA")
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1539"
name = "Steal Web Session Cookie"
reference = "https://attack.mitre.org/techniques/T1539/"

[[threat.technique]]
id = "T1555"
name = "Credentials from Password Stores"
reference = "https://attack.mitre.org/techniques/T1555/"
[[threat.technique.subtechnique]]
id = "T1555.003"
name = "Credentials from Web Browsers"
reference = "https://attack.mitre.org/techniques/T1555/003/"



[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[internal]
min_endpoint_version = "7.15.0"
