[rule]
description = """
Identifies when the Credential Vault Client library is loaded by an unusual process. Adversaries may acquire credentials
from Vault files.
"""
id = "048737fe-80d6-4462-aa80-ffeed853103e"
license = "Elastic License v2"
name = "Suspicious Vault Client Image Load"
os_list = ["windows"]
reference = [
    "https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.passwordvault.retrieve?view=winrt-22000",
]
version = "1.0.14"

query = '''
sequence by process.entity_id with maxspan=1m
 [process where event.action == "start" and
  (
   (process.executable : "?:\\Windows\\Microsoft.NET\\*.exe" and
    not process.executable : "?:\\Windows\\Microsoft.NET\\Framework64\\*\\dfsvc.exe") or

   process.name : ("regsvr32.exe", "mshta.exe", "notepad.exe", "msbuild.exe", "regasm.exe", "notepad.exe", "calc.exe") or

   (process.name : "rundll32.exe" and process.args : "?:\\Users\\*\\AppData\\*" and
    not process.args : ("url.dll,FileProtocolHandler", "cryptext.dll,CryptExtOpen*",
                        "?:\\WINDOWS\\system32\\mshtml.dll,PrintHTML", "shdocvw.dll,OpenURL")) or

   (process.name : "rundll32.exe" and process.args_count == 1) or

   (process.name : "powershell.exe" and process.args : ("-enc", "-ec", "-e", "*downloadstring*", "*Reflection.Assembly*")) or

   (process.Ext.device.product_id : ("Virtual DVD-ROM", "Virtual Disk") and not process.executable : "C:\\*") or

   process.command_line : "\"{path}\""
   ) and

   not (process.name : "powershell.exe" and
        process.parent.executable :
               ("?:\\Program Files (x86)\\Dell\\UpdateService\\ServiceShell.exe",
                "?:\\Windows\\System32\\wsl.exe",
                "?:\\Windows\\Explorer.exe")) and
   not (process.name : "ngen.exe" and process.parent.name : "NGenTask.exe") and
   not (process.name : "calc.exe" and process.parent.executable : "?:\\Windows\\Explorer.exe") and
   not process.parent.executable : ("?:\\Program Files (x86)\\Lenovo\\LeAppStore\\LeASPac.exe",
                                    "?:\\Program Files\\Dell\\DellOptimizer\\DellOptimizer.exe",
                                    "?:\\Program Files\\WindowsApps\\Microsoft.*.exe",
                                    "?:\\Program Files (x86)\\LabTech Client\\LTClient.exe",
                                    "?:\\Users\\*\\AppData\\Local\\StarlimsBridge\\StarlimsBridge.exe",
                                    "?:\\ProgramData\\LogiShrd\\LogiOptions\\Software\\Current\\LogiOptionsMgr.exe",
                                    "?:\\Windows\\System32\\DriverStore\\FileRepository\\*.exe") and
   not (process.name : ("powershell.exe", "mshta.exe") and process.working_directory : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*")) and
   not process.executable :
              ("?:\\Program Files\\WindowsApps\\Microsoft.WindowsNotepad_*\\Notepad\\Notepad.exe",
               "?:\\Windows\\Microsoft.NET\\Framework*\\dw20.exe") and
   not (process.name : ("rundll32.exe", "regsvr32.exe") and process.args : ("?:\\Program Files (x86)\\*", "?:\\Program Files\\*")) and
   not (process.name : "rundll32.exe" and process.command_line : "*MSI*.tmp,zzzzInvokeManagedCustomActionOutOfProc*")
  ]
 [library where dll.name : "vaultcli.dll"]
'''

min_endpoint_version = "8.4.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1555"
name = "Credentials from Password Stores"
reference = "https://attack.mitre.org/techniques/T1555/"
[[threat.technique.subtechnique]]
id = "T1555.004"
name = "Windows Credential Manager"
reference = "https://attack.mitre.org/techniques/T1555/004/"



[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[internal]
min_endpoint_version = "8.4.0"
