[rule]
description = """
Detects when a link is created to the temp directory. Threat actors have utilized this technique when attempting to
masqurade behind a legitimate application by droppinig their payload in the temp directory and linking it to the
legitimate application.
"""
id = "ccca5e9f-2625-4b95-9b15-d5d8fc56df2c"
license = "Elastic License v2"
name = "Link Creation to Temp Directory"
os_list = ["macos"]
reference = ["https://www.jamf.com/blog/cryptojacking-macos-malware-discovered-by-jamf-threat-labs"]
version = "1.0.4"

query = '''
process where event.type == "start" and 
    process.name : "ln" and process.args : "-s" and process.args : "/tmp/*" and not 
    process.parent.name : ("package_script_service", "installer")
'''

min_endpoint_version = "8.1.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"
[[threat.technique.subtechnique]]
id = "T1036.005"
name = "Match Legitimate Name or Location"
reference = "https://attack.mitre.org/techniques/T1036/005/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.1.0"
