[rule]
description = """
Identifies suspicious execution from an installer via Managed Custom Action. Adversaries may abuse msiexec.exe
installers with malicious custom actions to install malware.
"""
id = "68c8d90f-6cec-44bd-af40-d0082c49db0b"
license = "Elastic License v2"
name = "Execution via Windows Installer Managed Action"
os_list = ["windows"]
reference = [
    "https://lolbas-project.github.io/lolbas/Binaries/Msiexec/",
    "https://learn.microsoft.com/en-us/windows/win32/msi/custom-actions",
]
version = "1.0.8"

query = '''
process where event.action == "start" and not user.id : "S-1-5-18" and
 process.parent.name : "rundll32.exe" and process.parent.command_line : "*zzzzInvokeManagedCustomActionOutOfProc*" and
  (
   process.name : ("rundll32.exe", "regsvr32.exe", "cmd.exe", "powershell.exe", "msbuild.exe", "mshta.exe", "wscript.exe", "cscript.exe") or
   (process.executable : ("?:\\Users\\*\\AppData\\*", "?:\\ProgramData\\*", "?:\\Users\\Public\\*") and process.code_signature.exists == false) or
   (process.executable : "?:\\Windows\\Microsoft.NET\\*" and not process.name : "csc.exe")
  ) and
  not (process.name : "powershell.exe" and process.command_line : "* -Version * -s -NoLogo -NoProfile*") and
  not (process.name : "cmd.exe" and
       process.command_line : ("\"cmd.exe\" /C Ver",
                               "\"cmd.exe\"",
                               "\"cmd\" /c dotnet --list-runtimes",
                               "\"cmd.exe\" /c pnputil /enum-drivers",
                               "*:\\Program Files (x86)\\*",
                               "*:\\Program Files\\*",
                               "*sc.exe delete*",
                               "*/c pnputil*",
                               "*?:\\WINDOWS\\system32\\drivers*",
                               "\"cmd.exe\" /c set",
                               "* sc failure *",
                               "* sc start *",
                               "* sc config *",
                               "* net start *",
                               "*BlueJeans\\BlueJeans.Detector.exe*",
                               "*rewrite_amd64_en-US.msi *",
                               "*\\Argus3\\Tools\\configure_pdfprinter.cmd*")) and
  not (process.name : "regasm.exe" and process.parent.args : "Smartbar.Installer.CustomActions!Linkury.Installer.CustomActions.CustomActions.InstallationComplete") and 
  not (process.name : "powershell.exe" and process.command_line : "\"powershell\" Set-NetIPInterface \"Twingate\" -InterfaceMetric 1") and
  not process.hash.sha256 :
            ("8ecaaf20c18ab003723fa8a7c6a899fc46b0b1a34eb748b07ab8a0c2fe9fc35d",
             "1106b9f8fe6f7d68cd1c35006aba4add4dc204c9c960afd698f150a63bde5c7f",
             "4afd03745958fc80b12086faf92cfd198236f7f99c462a3fdf35bd8249cffbd8") and
  not (process.name : "cmd.exe" and process.parent.args : "RestoreScheduledTasks!RestoreScheduledTasks.CustomActions.GetTaskStatus") and
  not (process.name : "rundll32.exe" and process.command_line : "\"?:\\Windows\\System32\\rundll32.exe\" dfshim CleanOnlineAppCache") and
  not process.executable : "?:\\Windows\\Microsoft.NET\\Framework*" and
  not (process.name : ("regsvr32.exe", "regasm.exe") and process.args : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*")) and
  not (process.name : ("regsvr32.exe", "regasm.exe") and process.working_directory : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*")) and
  not (process.executable : "C:\\Argus3\\Tools\\Regsvr32.exe" and process.args : "C:\\Argus3\\*.dll")
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1218"
name = "System Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"
[[threat.technique.subtechnique]]
id = "T1218.007"
name = "Msiexec"
reference = "https://attack.mitre.org/techniques/T1218/007/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
