[rule]
description = """
Identifies the execution of a shell or python script from within a macOS application bundle. This may indicate an
attempt to bypass macOS Gatekeeper via a fake app bundle.
"""
id = "94a891a9-3771-4a8c-a6ca-82fa66cfd7e2"
license = "Elastic License v2"
name = "Script Execution via macOS Application Bundle"
os_list = ["macos"]
reference = [
    "https://cedowens.medium.com/macos-gatekeeper-bypass-2021-edition-5256a2955508",
    "https://kyle-bailey.medium.com/detecting-macos-gatekeeper-bypass-cve-2021-30657-cc986a9bc751",
    "https://objective-see.com/blog/blog_0x64.html",
]
version = "1.0.18"

query = '''
sequence with maxspan=5m
 [ process where event.action == "exec" and
   process.name : ("bash", "dash", "sh", "tcsh", "csh", "zsh", "ksh", "fish", "python*") and
   process.command_line : "*.app/Contents/MacOS/*-psn*" and process.parent.name : ("launchd", "xpcproxy") and
   not process.command_line :
                   ("*SHIELD Check*",
                    "*/Python */IDLE*.app/Contents/Resources/idlemain.py*",
                    "*/Applications/Python */IDLE.app/Contents/MacOS/IDLE -ps*",
                    "*Scripts/com.adobe.acrobat.AcroRdrDCUpd*", "*homebrew*",
                    "*/Applications/VisualVM.app/*")
 ] by process.pid
 [ process where event.action == "exec" and
   process.parent.name : ("bash", "dash", "sh", "tcsh", "csh", "zsh", "ksh", "fish", "python*") and
   process.name :
          ("curl",
           "mktemp",
           "tail",
           "funzip",
           "chmod",
           "python*",
           "osascript",
           "open",
           "bash",
           "dash",
           "sh",
           "tcsh",
           "csh",
           "zsh",
           "ksh",
           "fish",
           "perl") and
   not process.command_line : ("open steam://run/*", "/bin/sh -c uname -p 2> /dev/null")
 ] by process.parent.pid
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"

[[threat.technique.subtechnique]]
id = "T1059.006"
name = "Python"
reference = "https://attack.mitre.org/techniques/T1059/006/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1553"
name = "Subvert Trust Controls"
reference = "https://attack.mitre.org/techniques/T1553/"
[[threat.technique.subtechnique]]
id = "T1553.001"
name = "Gatekeeper Bypass"
reference = "https://attack.mitre.org/techniques/T1553/001/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
