[rule]
description = """
Adversaries may attempt to disable Security-Enhanced Linux (SELinux), which is a Linux kernel security feature to
support access control policies. Adversaries may disable security tools or logging serives to avoid possible detection
of their tools and activities.
"""
id = "b63df89d-ac6f-44d7-80fa-ddf038295e42"
license = "Elastic License v2"
name = "Attempt to Disable Linux Security and Logging Controls"
os_list = ["linux"]
version = "1.0.10"

query = '''
process where event.type=="start" and

 (  /* modify SELinux mode to permissive */
  ( process.name == "setenforce" and process.args == "0") or
  /* stop security or syslog service  */
  (
    (
      (process.name == "service" and process.args == "stop") or
      (process.name == "chkconfig" and process.args == "off") or
      (process.name == "systemctl" and process.args in ("disable","stop","kill"))or
      (process.name == "sysctl")
    ) and  process.args in ("apparmor","kernel.nmi_watchdog=0","syslog","rsyslog","syslog-ng")
  )
  ) and
  not process.parent.executable : ("/usr/local/cpanel/bin/taskrun", "/opt/alfresco-*/alfresco.sh", "/sbin/*")
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.parent.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1562"
name = "Impair Defenses"
reference = "https://attack.mitre.org/techniques/T1562/"
[[threat.technique.subtechnique]]
id = "T1562.001"
name = "Disable or Modify Tools"
reference = "https://attack.mitre.org/techniques/T1562/001/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
