[rule]
description = """
Identifies attempts to load an unsigned DLL from a mounted virtual disk (.iso, .vhd) and by a signed Microsoft binary.
This may indicate an attempt to sideload a malicious DLL to stealthily execute code.
"""
id = "ba802fb2-f183-420e-947b-da5ce0c74dd3"
license = "Elastic License v2"
name = "Potential DLL SideLoad via a Microsoft Signed Binary"
os_list = ["windows"]
version = "1.0.10"

query = '''
/* MS bin used as DLL sideloading target from an ISO/DMG/VHD archive */
library where
  dll.Ext.device.product_id : ("Virtual DVD-ROM", "Virtual Disk") and
  process.code_signature.subject_name : "Microsoft*" and
  not dll.code_signature.status : ("trusted", "errorExpired", "errorCode_endpoint*", "errorChaining") and
  not process.executable : "C:\\*" and
  not startswith~(dll.name, process.name)
'''

min_endpoint_version = "8.4.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1574"
name = "Hijack Execution Flow"
reference = "https://attack.mitre.org/techniques/T1574/"
[[threat.technique.subtechnique]]
id = "T1574.001"
name = "DLL Search Order Hijacking"
reference = "https://attack.mitre.org/techniques/T1574/001/"

[[threat.technique.subtechnique]]
id = "T1574.002"
name = "DLL Side-Loading"
reference = "https://attack.mitre.org/techniques/T1574/002/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.4.0"
