[rule]
description = """
Detects deletion of the quarantine attribute by an unusual process (xattr). In macOS, when applications or programs are
downloaded from the internet, there is a quarantine flag set on the file. This attribute is read by Apple's Gatekeeper
defense program at execution time. An adversary may disable this attribute to evade defenses.
"""
id = "ab595e22-ca96-4b33-9dc9-47e4a77c7895"
license = "Elastic License v2"
name = "Quarantine Attrib Removed by Usigned or Unstrusted Process"
os_list = ["macos"]
reference = [
    "https://nixhacker.com/security-protection-in-macos-1/",
    "https://eclecticlight.co/2020/10/29/quarantine-and-the-quarantine-flag/",
]
version = "1.0.13"

query = '''
file where event.action == "extended_attributes_delete" and process.executable != null and
(process.code_signature.trusted == false or process.code_signature.exists == false) and not
process.executable : ("/usr/bin/xattr", 
                      "/System/*", 
                      "/private/tmp/KSInstallAction.*/*/Install Google Software Update.app/Contents/Helpers/ksinstall",
                      "/Applications/CEWE Fotoschau.app/Contents/MacOS/FotoPlus",
                      "/Applications/.com.bomgar.scc.*/Remote Support Customer Client.app/Contents/MacOS/sdcust") and not
file.path : "/private/var/folders/*"
'''

min_endpoint_version = "8.3.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1553"
name = "Subvert Trust Controls"
reference = "https://attack.mitre.org/techniques/T1553/"
[[threat.technique.subtechnique]]
id = "T1553.001"
name = "Gatekeeper Bypass"
reference = "https://attack.mitre.org/techniques/T1553/001/"


[[threat.technique]]
id = "T1562"
name = "Impair Defenses"
reference = "https://attack.mitre.org/techniques/T1562/"
[[threat.technique.subtechnique]]
id = "T1562.001"
name = "Disable or Modify Tools"
reference = "https://attack.mitre.org/techniques/T1562/001/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.3.0"
