[rule]
description = """
Identifies the execution of a command via Microsoft Visual Studio Pre or Post build events. Adversaries may backdoor a
trusted visual studio project to execute a malicious command during the project build process.
"""
id = "74be6307-2d15-4c71-8072-fc606f337a51"
license = "Elastic License v2"
name = "Execution via MS VisualStudio Pre/Post Build Events"
os_list = ["windows"]
reference = [
    "https://docs.microsoft.com/en-us/visualstudio/ide/reference/pre-build-event-post-build-event-command-line-dialog-box?view=vs-2022",
    "https://www.pwc.com/gx/en/issues/cybersecurity/cyber-threat-intelligence/threat-actor-of-in-tur-est.html",
    "https://blog.google/threat-analysis-group/new-campaign-targeting-security-researchers/",
    "https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Execution/execution_evasion_visual_studio_prebuild_event.evtx",
]
version = "1.0.15"

query = '''
sequence with maxspan=1m
 [process where event.action == "start" and
  process.name : "cmd.exe" and process.parent.name : "MSBuild.exe" and
  process.args : "?:\\Users\\*\\AppData\\Local\\Temp\\tmp*.exec.cmd"] by process.entity_id
 [process where event.action == "start" and
  process.name : ("cmd.exe",
                  "powershell.exe",
                  "MSHTA.EXE",
                  "CertUtil.exe",
                  "CertReq.exe",
                  "rundll32.exe",
                  "regsvr32.exe",
                  "MSbuild.exe",
                  "cscript.exe",
                  "wscript.exe",
                  "installutil.exe") and
  not (process.name : ("cmd.exe", "powershell.exe") and
       process.args : ("HKLM\\SOFTWARE\\Microsoft\\VisualStudio\\SxS\\VS?",
                       "process.versions.node*",
                       "?:\\Program Files\\nodejs\\\\node.exe",
                       "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\MSBuild\\ToolsVersions\\*",
                       "*Get-ChildItem*Tipasplus.css*",
                       "Build\\GenerateResourceScripts.ps1",
                       "Shared\\Common\\..\\..\\BuildTools\\ConfigBuilder.ps1\"",
                       "?:\\Projets\\*\\PostBuild\\MediaCache.ps1")) and
  not process.executable : "?:\\Program Files*\\Microsoft Visual Studio\\*\\MSBuild.exe"
  ] by process.parent.entity_id
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1127"
name = "Trusted Developer Utilities Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1127/"
[[threat.technique.subtechnique]]
id = "T1127.001"
name = "MSBuild"
reference = "https://attack.mitre.org/techniques/T1127/001/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
