[rule]
description = """
An adversary may attempt to get detailed information about the operating system and hardware. This rule identifies
common locations used to discover virtual machine hardware by a non-root user.
"""
id = "e5c0963c-0367-4d24-bdf2-5af3a233e57b"
license = "Elastic License v2"
name = "Potential Virtual Machine Fingerprinting via Grep"
os_list = ["macos"]
reference = ["https://objective-see.com/blog/blog_0x4F.html"]
version = "1.0.16"

query = '''
process where event.type == "start" and process.name in ("grep", "egrep") and 
 (process.command_line : "*parallels*" and process.command_line : "*virtualbox*" and process.command_line : "*vmware*") and
 not process.parent.executable in ("/Applications/Docker.app/Contents/MacOS/Docker", "/usr/libexec/kcare/virt-what")
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1082"
name = "System Information Discovery"
reference = "https://attack.mitre.org/techniques/T1082/"

[[threat.technique]]
id = "T1497"
name = "Virtualization/Sandbox Evasion"
reference = "https://attack.mitre.org/techniques/T1497/"
[[threat.technique.subtechnique]]
id = "T1497.001"
name = "System Checks"
reference = "https://attack.mitre.org/techniques/T1497/001/"



[threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

[internal]
min_endpoint_version = "7.15.0"
