[rule]
description = """
Detects the execution of the Nohup utility pointing to a suspicious or malicious executable path followed by pushing the
execution to the background using the "&". Threat actors will utilize the Nohup utility to execute their payloads in a
variety of ways but specifically within initial access installer scripts and shell profile persistence. This activity
should be considered highly abnormal or malicious.
"""
id = "3f18726c-4897-41dc-8426-15da95b8482f"
license = "Elastic License v2"
name = "Suspicious Nohup Execution"
os_list = ["macos"]
reference = ["https://objective-see.org/blog/blog_0x71.html"]
version = "1.0.5"

query = '''
process where event.type == "start" and 
process.name : "nohup" and 
process.command_line : ("*/tmp/*&", 
                        "*/var/folders/*&", 
                        "*/Users/Shared/*&", 
                        "*/Library/*&", 
                        "*/var/root/*&", 
                        "*/usr/local/bin/*&", 
                        "*/Applications/*&") and
process.parent.name : ("bash", "sh", "zsh", "tclsh*", "terminal")
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1564"
name = "Hide Artifacts"
reference = "https://attack.mitre.org/techniques/T1564/"
[[threat.technique.subtechnique]]
id = "T1564.003"
name = "Hidden Window"
reference = "https://attack.mitre.org/techniques/T1564/003/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
