[rule]
description = """
Identifies the load of a library from a removable media. Adversaries may move onto systems, possibly those on
disconnected or air-gapped networks, by copying malware to removable media and taking advantage of Autorun features when
the media is inserted into a system and executes.
"""
id = "91ca1c5d-f6f1-46e1-9ad5-3336e67cf50a"
license = "Elastic License v2"
name = "Suspicious DLL Loaded from a Removable Media"
os_list = ["windows"]
version = "1.0.9"

query = '''
library where
 (dll.Ext.device.bus_type : "usb" or dll.Ext.device.product_id : "USB *") and
 process.code_signature.trusted == true and
 process.executable != null and
 not dll.code_signature.status : ("trusted", "errorExpired", "errorCode_endpoint*", "errorChaining") and
 not startswith~(dll.name, process.name) and

 (
  /* DLL loaded from the process.executable current directory */
  endswith~(substring(dll.path, 0, length(dll.path) - (length(dll.name) + 1)), substring(process.executable, 0, length(process.executable) - (length(process.name) + 1)))  or

  /* common Lolbins used to run a DLL */
  process.name : ("rundll32.exe", "regsvr32.exe")
  ) and

 not process.code_signature.subject_name :
       ("Johannes Schindelin",
       "DVR Support Center",
       "InfoCert SpA",
       "Intuit",
       "INTUIT INC.",
       "Merge Healthcare Inc.",
       "Code Systems Corporation",
		"Pogopixels Ltd", 
		"Riot Games, Inc.", 
		"Valve Corp.", 
		"Mozilla Corporation", 
		"PFU Limited", 
		"MITSUBISHI ELECTRIC CORPORATION", 
		"Macrovision Corporation", 
		"Buhl Data Service GmbH", 
		"FromSoftware,Inc.", 
		"Milestone Systems A/S", 
		"Magnet Forensics Inc.", 
		"Jernej Simončič", 
		"Data Locker Inc.", 
		"Merge Healthcare Incorporated", 
		"Philips Healthcare Informatics, Inc.", 
		"INFOCERT SPA CODESIGN", 
		"Imation Corp",
		"Turning Technologies, LLC",
		"Magix AG",
		"Intuit Inc",
		"CISCO SYSTEMS, INC.",
		"SEIKO EPSON CORPORATION",
		"Sage South Africa (Pty) Ltd")
'''

min_endpoint_version = "8.4.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1091"
name = "Replication Through Removable Media"
reference = "https://attack.mitre.org/techniques/T1091/"


[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"

[internal]
min_endpoint_version = "8.4.0"
