[rule]
description = """
Identifies the creation of executable files in a removable media and by an unusual process. Adversaries may move onto
systems, possibly those on disconnected or air-gapped networks, by copying malware to removable media and taking
advantage of Autorun features when the media is inserted into a system and executes.
"""
id = "6d9b4bb0-1262-4cc1-8e65-3f4758ceaaad"
license = "Elastic License v2"
name = "Executable File Creation in a Removable Media"
os_list = ["windows"]
version = "1.0.9"

query = '''
file where event.action != "deletion" and process.name != null and

 (file.Ext.device.bus_type : "usb" or file.Ext.device.product_id : "USB *") and

 not process.executable :
         ("?:\\Windows\\explorer.exe",
          "?:\\Program files\\*.exe",
          "?:\\Program Files (x86)\\*.exe",
          "?:\\Windows\\System32\\Robocopy.exe",
          "?:\\Windows\\System32\\xcopy.exe",
          "?:\\$Windows.~WS\\Sources\\SetupHost.exe",
          "\\Device\\Mup\\*",
          "?:\\temp\\EstimatingInstallerUpdate_*\\Prerequisites\\DotNet\\ndp*-allos-enu.exe",
          "?:\\Autodesk\\Autodesk_Navisworks_Freedom_*\\3rdParty\\x64\\VCRedist\\*\\vcredist_x64.exe",
          "?:\\Windows\\SoftwareDistribution\\Download\\*.exe",
          "?:\\Windows\\System32\\RecoveryDrive.exe",
          "?:\\Windows\\System32\\dllhost.exe",
          "?:\\Users\\*\\AppData\\Local\\Temp\\is-*.tmp\\ECM Titanium-3.0-Setup*.tmp",
          "?:\\Users\\*\\AppData\\Local\\Temp\\ns*.tmp\\7zG.exe") and

 (file.Ext.header_bytes : "4d5a*" or
  file.extension : ("exe", "scr", "pif", "com", "js", "vbs", "wsh", "hta", "cpl", "jse", "vbe", "lnk", "iqy", "slk", "iqy",
                    "cmd", "bat", "library-ms", "glk", "url", "scf", "chm")) and
  process.pid != 4 and

  /* avoid reporting processes running from the USB itself */
  not startswith~(substring(process.executable, 0, 1), substring(file.path, 0, 1)) and

  not (process.code_signature.subject_name :
               ("Akeo Consulting",
                "Eric R. Zimmerman",
                "Lenovo",
                "ClevX LLC",
                "Buhl Data Service GmbH",
                "Super Flexible Software Ltd. & Co. KG",
                "InfoCert SpA",
                "Overwolf Ltd",
                "Dell Technologies Inc.",
                "Microsoft Corporation", 
                "Shenzhen iSunshare Software Co., Ltd.", 
                "Software Technology, LLC",
                "Rare Ideas, LLC",
                "Seagull Scientific Inc.") and
       process.code_signature.trusted == true) and
  not (process.name : "powershell.exe" and file.path : "?:\\KAPE_UofUDev\\KAPE\\KAPE\\Modules\\bin\\RECmd\\Plugins\\*") and
  not (process.executable : "?:\\Windows\\System32\\svchost.exe" and file.path : "?:\\FileHistory\\*") and
  not (process.name : "YUMI-*.exe" and file.path : ("?:\\multiboot\\wimboot", "?:\\multiboot\\grub.exe")) and
  not (process.name : "CRS600.exe" and file.path : "?:\\NFTA *\\Rev100\\USERDATA\\DR700_UPDATE.EXE")
'''

min_endpoint_version = "8.4.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1091"
name = "Replication Through Removable Media"
reference = "https://attack.mitre.org/techniques/T1091/"


[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"

[internal]
min_endpoint_version = "8.4.0"
