[rule]
description = """
Identifies attempts to bypass User Account Control (UAC) via ShellExecute RunAS method. Attackers may attempt to bypass
UAC to execute code with high integrity via malicious documents or scripts.
"""
id = "7609ebb3-0154-431b-badc-264b10527d13"
license = "Elastic License v2"
name = "Elevated Execution via ShellExecute RunAs Administrator"
os_list = ["windows"]
reference = [
    "https://www.winhelponline.com/blog/vbscripts-and-uac-elevation/",
    "https://github.com/S3cur3Th1sSh1t/OffensiveVBA/blob/main/src/ShellApplication_ShellExecute_privileged.vba",
]
version = "1.0.17"

query = '''
sequence with maxspan=5m
 [process where event.action == "start" and
  process.name : ("WINWORD.EXE",
                  "EXCEL.EXE",
                  "POWERPNT.EXE",
                  "MSACCESS.EXE",
                  "cscript.exe",
                  "mshta.exe") and
  process.Ext.token.integrity_level_name == "medium"] by process.entity_id
 [process where event.action == "start" and
  /*
    processes started via ShellApplication.ShellExecute.runas
    will have high integrity and real parent set to AppInfo
  */
  process.Ext.token.integrity_level_name == "high" and process.parent.Ext.real.pid > 0 and

  not (process.pe.original_file_name == "OfficeC2RClient.exe" and
       process.code_signature.subject_name == "Microsoft Corporation" and process.code_signature.trusted == true) and

  not (process.pe.original_file_name == "Acrobat.exe" and
       process.code_signature.subject_name == "Adobe Inc." and process.code_signature.trusted == true) and

  not process.executable :
              ("?:\\Program Files (x86)\\*.exe",
               "?:\\Program Files\\*.exe",
               "?:\\Windows\\System32\\ntprint.exe",
               "?:\\Windows\\SysWOW64\\ntprint.exe") and
  not (process.executable : "?:\\ProgramData\\chocolatey\\bin\\choco.exe" and process.parent.name : "cscript.exe" and
       process.parent.args : "?:\\ProgramData\\chocolatey\\lib\\Sudo\\bin\\sudo.vbs")
  ] by process.parent.entity_id
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1566"
name = "Phishing"
reference = "https://attack.mitre.org/techniques/T1566/"
[[threat.technique.subtechnique]]
id = "T1566.001"
name = "Spearphishing Attachment"
reference = "https://attack.mitre.org/techniques/T1566/001/"



[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.005"
name = "Visual Basic"
reference = "https://attack.mitre.org/techniques/T1059/005/"

[[threat.technique.subtechnique]]
id = "T1059.007"
name = "JavaScript"
reference = "https://attack.mitre.org/techniques/T1059/007/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1548"
name = "Abuse Elevation Control Mechanism"
reference = "https://attack.mitre.org/techniques/T1548/"
[[threat.technique.subtechnique]]
id = "T1548.002"
name = "Bypass User Account Control"
reference = "https://attack.mitre.org/techniques/T1548/002/"



[threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1218"
name = "System Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"
[[threat.technique.subtechnique]]
id = "T1218.005"
name = "Mshta"
reference = "https://attack.mitre.org/techniques/T1218/005/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
