[rule]
description = """
Identifies the creation of a driver file by an untrusted program and subsequently loaded in the kernel. Adversaries may
bring a driver onto a compromised machine to execute code with the highest privileges.
"""
id = "3f1cbf09-dba1-428d-8c84-a86db573889e"
license = "Elastic License v2"
name = "Driver Dropped by Untrusted Executable"
os_list = ["windows"]
version = "1.0.17"

query = '''
sequence with maxspan=5m
 [file where event.action != "deletion" and
  (file.extension : "sys" or file.Ext.header_bytes : "4d5a*") and
  (process.code_signature.trusted == false or process.code_signature.exists == false) and
  not process.executable : ("?:\\Windows\\System32\\drvinst.exe",
                            "?:\\ProgramData\\Lenovo\\*.EXE",
                            "?:\\Program Files (x86)\\*.exe",
                            "?:\\Program Files\\*.exe",
                            "?:\\Windows\\System32\\msiexec.exe",
                            "?:\\Windows\\SoftwareDistribution\\Download\\*") and
  not process.code_signature.status : ("errorTimeStamp", "errorCode_endpoint*", "errorExpired", "errorUntrustedRoot", "errorChaining") and
  not (process.executable : "?:\\Windows\\Temp\\*\\NIC_Intel_Firmware\\nvmupdatew64e.exe" and file.path : "?:\\Windows\\System32\\drivers\\iqvw64e.sys")] by file.path
 [library where process.pid == 4 and
  not dll.pe.imphash :
          ("0109bf02bbd845b03c84c9676bdd8869",
           "70dfb19ec9802de85e2d68ccd3e0a42b",
           "b35b4e570041a8cb73f5e6afa1fd5c7d",
           "a5133e97cadbd737ec8e8341ca24aa55",
           "d41fa95d4642dc981f10de36f4dc8cd7",
           "0cdcd611bd5dba23c5f365d9ae0e27f3",
           "58623490691babe8330adc81cd04a663",
           "bfc88c1c5b6d829a4bab7a165d25d83f",
           "d0b73a9defa3459abe55bae4cd1f844f",
           "e54cb614fcaa06fed22c681d4526d8bf",
           "f86759bb4de4320918615dc06e998a39",
           "b8022367f73cdbdb08bb0667e4088757",
           "dc8acd7d20149d09a6c261c7a5f609c4",
           "db4408247c447c666c12863d8fa61ff5",
           "b05ee5c816a30bc52378c759486af0b9",
           "861b526e8a3269e3024aa5d3f5adbe82",
           "8d447341046e42fa55c9bee87728e772",
           "4ecb36c0b2723d787fab469707d85651",
           "c51e532cddc815f09d5892bba99352e2",
           "596983b0a04a95e4261a4f893103c16e",
           "5f4d38669edea237e4e569abdfb7a2e5",
           "26d49feec51abdaa0b95edec8a8754b9",
           "55db306bc2be3ff71a6b91fd9db051b8", 
           "cb86059f4b291991e735becbd4c669cb", 
           "ce753744099dc03f568621989387593a", 
           "3990ca8c997ab070d46f7721f45f3cb0", 
           "c8859630c2336b43f2c02654dfdc5aea") and
   not (dll.code_signature.subject_name : ("FinalWire Kft.", "Musaruba US LLC") and dll.code_signature.trusted == true)] by dll.path
'''

min_endpoint_version = "8.0.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1068"
name = "Exploitation for Privilege Escalation"
reference = "https://attack.mitre.org/techniques/T1068/"

[[threat.technique]]
id = "T1543"
name = "Create or Modify System Process"
reference = "https://attack.mitre.org/techniques/T1543/"
[[threat.technique.subtechnique]]
id = "T1543.003"
name = "Windows Service"
reference = "https://attack.mitre.org/techniques/T1543/003/"



[threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"

[internal]
min_endpoint_version = "8.0.0"
